// <auto-generated />
using LinMeyer.GooglePhotosBackup.Asp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinMeyer.GooglePhotosBackup.Asp.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20230325215913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("LinMeyer.GooglePhotosBackup.Asp.Data.FileStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
